"""create all necessary tables

Revision ID: 42457931e38c
Revises: 0002_add_rejected
Create Date: 2026-05-15 08:21:02.541952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42457931e38c'
down_revision = '0002_add_rejected'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_candidate_profiles_id'), 'candidate_profiles', ['id'], unique=False)
    op.create_table('job_offer_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_report', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offer_reviews_id'), 'job_offer_reviews', ['id'], unique=False)
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_mime_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_documents_id'), 'application_documents', ['id'], unique=False)
    op.create_table('email_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_notifications_id'), 'email_notifications', ['id'], unique=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('applications', 'resume_url')
    op.add_column('job_offers', sa.Column('status', sa.String(length=50), nullable=True))
    op.alter_column('job_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('job_offers', 'is_published')
    op.drop_column('job_offers', 'is_rejected')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('job_offers', sa.Column('is_rejected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('job_offers', sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.alter_column('job_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('job_offers', 'status')
    op.add_column('applications', sa.Column('resume_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_email_notifications_id'), table_name='email_notifications')
    op.drop_table('email_notifications')
    op.drop_index(op.f('ix_application_documents_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_job_offer_reviews_id'), table_name='job_offer_reviews')
    op.drop_table('job_offer_reviews')
    op.drop_index(op.f('ix_candidate_profiles_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###